unique_ids:
  assets:
    standard-page.html: KTXMCNRAYKUZ5BBEWBRED3CEZPDLRAPN
    theme.css: J7PZIHJMEMXA2CBKI6DUT4GKGIG2AIFG
  forms:
    Form1: TZIMFZ6KZWUNZPFLBYB4UQD4OJ6NOVU3
  modules: {}
  scripts: {}
  server_modules: {}
